services:
    app:
      ports:
        - "8000:8000"
      volumes:
        - ./docker/supervisor/common.conf:/etc/supervisor/common.conf
        - ./docker/supervisor/prod.conf:/etc/supervisor/conf.d/supervisord.conf
        - ./Caddyfile:/etc/caddy/Caddyfile

