global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'laravel-app'
    static_configs:
      - targets: ['app:80']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187'] # Для postgres_exporter

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121'] # Для redis_exporter
